# Generated by Django 5.2.4 on 2025-10-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
