# Generated by Django 5.2.4 on 2025-10-02 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='internship_thumbnails/')),
                ('description', models.TextField()),
                ('field', models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile App Development', 'Mobile App Development'), ('Game Development', 'Game Development'), ('Data Science / AI', 'Data Science / AI'), ('Cloud & DevOps', 'Cloud & DevOps')], max_length=50)),
                ('length_days', models.PositiveIntegerField(help_text='Duration of the internship in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_link', models.URLField(max_length=500)),
                ('fully_completed', models.BooleanField()),
                ('experience_feedback', models.TextField(blank=True, null=True)),
                ('difficulty_rating', models.CharField(choices=[('easy', 'Easy'), ('mid', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_reason', models.TextField(blank=True, help_text='Reason for rejection, if any.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed instructions for the task')),
                ('order', models.PositiveIntegerField(default=0)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='internships.internship')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('awaiting_evaluation', 'Awaiting Evaluation'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='in_progress', max_length=20)),
                ('is_started', models.BooleanField(default=False)),
                ('intro_completed', models.BooleanField(default=False)),
                ('roadmap_completed', models.BooleanField(default=False)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.internship')),
            ],
        ),
    ]
