# Generated by Django 5.2.4 on 2025-10-01 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userinternship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='user_internship',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='internships.userinternship'),
        ),
        migrations.AlterUniqueTogether(
            name='userinternship',
            unique_together={('user', 'internship')},
        ),
    ]
