# Generated by Django 5.2.4 on 2025-10-02 20:07

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail'),
        ),
        migrations.CreateModel(
            name='InternshipStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('learn', 'Learning Material'), ('task', 'Task & Submission')], default='learn', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, help_text="Main content for a 'Learning' step.")),
                ('external_link', models.URLField(blank=True, help_text="Optional: A link to a PDF, video, or article for a 'Learning' step.", max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='internships.internship')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
