# Generated by Django 5.2.4 on 2025-10-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_alter_internship_thumbnail_internshipstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinternship',
            name='completed_steps',
            field=models.ManyToManyField(blank=True, to='internships.internshipstep'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
