# Generated by Django 5.2.4 on 2025-10-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_userinternship_completed_steps_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinternship',
            name='completed_steps',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='internships.internshipstep'),
        ),
    ]
