# Generated by Django 5.2.4 on 2025-10-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_alter_userinternship_completed_steps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='internships.userinternship'),
        ),
    ]
